var input = `
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/AirsT0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Cosp0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010FallvAdjwk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010fallvc
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010fallvcOrogA
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010fallvcOrogB
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010fallvcOrogC
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010FallvDragOce
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010fallv
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010Fallv
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607Calot
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotMY1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotMY2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotMY33
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotOrogr
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotT0cosp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotT1cosp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotT2cosp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotTeta
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotTglace240
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotTglace250
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvAdiab
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvClosTh
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvCtrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvCtrlT0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvCtrlT1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvTop
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvWk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607svn2761
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v2Bds
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v3Ctrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v3T1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v4
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v5
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6lc23
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6oro
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6svn2828
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6tqsat
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6wb3p05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05MyLmGust
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05MyLm
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05MY
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6103bFlagPbl12
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6103b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ610v3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.4
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.5
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.70a
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.70aZ0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.80B
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70bOrolf
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2703
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2709Cosp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2709cv72
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2709
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80aa2714
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80aa
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Acv48
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Adtphy10cv72
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Adtphy10
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80A
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80B
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Bz0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81clos1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81clos2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81rim1cv48
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81rim1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81rim2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82alw
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82gkwak
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82svn2738
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82svn2739alw
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Calipso
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Cloudsat
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Isccp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Misr
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Modis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp01Subcln
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/ducharna/OL2/PROD/test3977/FG3WFDEIv1.new2combrsol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/ducharna/OL2/PROD/test3977/FG3WFDEIv1.newcombnorsol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/ducharna/OL2/PROD/test3977/FG3WFDEIv1.newcombrsol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/0aerstrat
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/EXP01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/oa5a
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/oa5b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/vol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/piControl/EXP00
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/PROD/pdControl/CM606-LR-pdCtrl-C03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.40RRTMsvn2456AER0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1DUST6w
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1DUST6wT
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1ORG2w
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1ORG6w
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1ORG
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT2w
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT6wa
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT6w
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.30Y.2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.rt0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM608-LR.30Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM608-LR.q2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPg-CM608-LR.30Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPgv-CM607-LR.30Y.2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPg.vt-CM607-LR.2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80bz0cwrr
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80bz0cwrr.q2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80-CM606-LR-b01bz0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80-CM606-LR-b01bz0.q
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80-CM606-LR-b01bz0.q.rt0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM608-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM608-LR-amip-G-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM609-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM609-LR-amip-01.q
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM609-LR-amip-G-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24balk/LMDZORINCA/DEVT/AER/Historical
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24balk/LMDZORINCA/PROD/AER/pdCtrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24balk/LMDZORINCA/PROD/AER/preInd2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6.0.10.04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6.04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05.2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis4
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis5
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-piCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-07
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-08
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-09
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZOR/PROD/clim/LMDZOR02bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZOR/PROD/clim/LMDZOR02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZOR/PROD/clim/LMDZOR03bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p25sepul/IPSLCM5A2/PROD/piControl/pi.orch.07.tun00
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p25sepul/IPSLCM5A2/PROD/piControl/speedtest.cmip6
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-etaumle
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nnetau0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nolnmle
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-rnffwb0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-rnffwb2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607.calving-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-CALMOC-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-CalvIce-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-CalvIce-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-CalvIce-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.dynroot
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.frz.frzc1.smtc2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref4365/CL4.4365.L2883
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.10spinup
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.cruncep.spinup
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.veg.const
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.veg.update
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA2.cruncep.vegconst
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA2.cruncep.vegupdate
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.cruncep.spinup
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.cruncep.vegconst
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.cruncep.vegupdate
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.spinup
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.vegconst
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.vegupdate
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.vegupdate.nodr
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.CWRR.3977c.comb.nors.bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.CWRR.3977c.comb.nors.dynroot
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.gswp3.CWRR.3977c.comb.Frz.frozc1.smtotc2.rsol.dynroot
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.gswp3.CWRR.3977c.comb.nors.Frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.gswp3.CWRR.3977c.comb.nors
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/test.esa.loc
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/test.wfdeilatlon.loc
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.frz.dynroot.4h
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.frz.dynroot
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.ks
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.usda
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.frz.dynroot
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.ks
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.usda
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nudgeUV12h
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nudgeUV
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.GUST.1-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.GUST-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.Z0-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.Z0.pstar10e3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.Z0.rnalbice058
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.Z0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.Z0.r2641bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.Z0.trunk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-gust-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-INIT-3DOCE
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-nudgeUV
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-nudgeUVT
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-NUDTS-3DOCE
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-G
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-G-nudUV
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-Gust
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-Gust-nudUV12
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-Gust-nudUV
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-FOR-ENSEMBLE
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-fqsat-Gust-nudUV12h
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-Gust-bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-Gust
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-Gust-nudUV12h
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/PROD/pdControl/CM605.Z0-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/amip/ERAI.CTRL.NUD
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/amip/LMDZOR.NUD.ERAISST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIP-CTRL
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-fdoce0.8
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-fdoce1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-nudUV12h
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-nudUV24h
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-nudUV
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-amip-Gust
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-amip-Gust-nudUV
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CTRL6.0.5b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CTRL6.0.5F
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CTRL6.0.5.foce
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR6.0.5GUST.1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.CTRL
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.3wk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.fdrag0.9
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.minwind
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.strato
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.Z0heqZ0m
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.GUST.NUD.fqsat
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.GUST.NUD
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.pre608G
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/NPv5.8GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/NPv5.8Z0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.GUSTB
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.GUST.ratqs
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.Z0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5bZ0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5.GUSTBF
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5.GUSTF
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5.Z0F
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.AMIP
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST.3wk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST.strato
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.Z0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.CLIM
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.CTRL
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST.2bl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST.cdrag
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST.minwind
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.CTRL.2004
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.CTRL.2007
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.CTRL
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST0wk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST.2004
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST.2007
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST3wk.2007
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST3wk
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST.strato
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.strato
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.Z0.2004
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.Z0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.Z0.cdrag
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.Z0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.Z0.qh
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86cadul/IPSLCM6/DEVT/pdControl/TCO2.00
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86cadul/IPSLCM6/DEVT/pdControl/TCO2.01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86cadul/IPSLCM6/DEVT/pdControl/TCO2.02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/pdControl/CM5A2-BILAN07
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/pdControl/CM5A2-BILAN08
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/pdControl/CM5A2-BILAN-NEWOASIS01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2.1-piControl.02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK-rev2642
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK-rev26621-bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK-rev26621
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/COURSNIV2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/pdControl/CM5A2-BILAN01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/pdControl/CM5A2-BILAN02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/pdControl/CM5A2-BILAN03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/piControl/CM5A2.1-piControl.03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/piControl/VERIFIPSLCM5A2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/historical/CM607-LR-historical-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/historical/CM607-LR-historical-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.1.ener-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.2.test-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.albedo-LR-pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.cdrag-LR-pdctrl-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.cld-LR-pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.cld-LR-pdctrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010-LR-pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.Ridging-LR-pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.Ridging-LR-pdctrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.Ridging-LR-pdctrl-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.SnwCnd-LR-pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.SnwCnd-LR-pdctrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.SnwCnd-LR-pdctrl-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM605-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM605-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM605.THC1-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606.calving-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606.calving-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan06
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan07
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs06
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs07
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs08
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs09
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs10
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs11
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs12
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs13
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs15
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs16
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs17
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.4-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.5-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.interp-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.interp-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.lmixmin-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM608-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609.xios-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609.xios-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609.xios-LR-pdCtrl-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/PRECM607
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/v2.CM6.0.4-pdctrl.0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM6010.2-LR-piCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM605-LR-piCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM607-LR-piCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM607.spinup-LR-piCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/PRECM5A2.6
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/PRECM5A2.7
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM607-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM607-LR-amip-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/OL2/DEVT/secsto/MYEXP2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/OL2/DEVT/secsto/MYEXP3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-FREEZE-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/pdControl/CM607-DISSIP-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/pdControl/CM607-EMBD2-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/piControl/WF.01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605-FREEZ-LR-sstClim-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605-LR-sstClim-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605.NOSU-LR-sstClim-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605-OZ-LR-sstClim-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM606-OZ-LR-sstClim-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-FREEZ-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-pstar10e3-pdCtrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-rnalbice058-pdCtrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-tglacemin253-pdCtrl
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6.0.10.1Test-Pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6.0.10.1Test-Pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6.0.10.3b-Pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6011pre-LR-pdCtrl-fallv-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6011pre-LR-pdCtrl-fallv-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6011pre-LR-pdCtrl-fallv
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01a
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01bz0-cplok
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01bz0
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.2-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.2mod-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.3.1-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.3.1mod-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.3-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR.newmy
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01cont
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-2bands-lucia
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-2bands
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-bQP037-GWD
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-bQP037
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-NPv6.0.7
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt14
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt16-lucia
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt16
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt16oce
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-optim
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-rim1607b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR.spin.newmy
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR.TRY
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608.3-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608.6-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608-LR-pdCtrl-gwdrag01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608-LR-pdCtrl-gwdrag02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-fcdragoce
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CMpre6010.4-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/lucia
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/PROD/pdControl/NPv5.70PDctrl01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/PROD/pdControl/NPv5.70PDLott
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/PROD/pdControl/v5.71vd2qsp375
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.2bands.full
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.2bands
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.2bands.opt
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.3bands
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-gkdrag2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-gkwake4
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607divx2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607gkdrag
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607gklift
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607gkwake
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607grotJM
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607grottempJM
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607ion
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607iterdiv2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607OrogAll
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607OrogFC
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607tempJM
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01contspin
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01spin
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/M607.veget-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/M607.veget-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM6010/createsnow
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m10b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m11b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m12b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m1b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m2b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m3b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m4b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m5b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m6b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m7b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m8b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m9b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.refb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.src3013b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3047/CL4.4067.L608.flp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3047/CL4.4067.L608
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.NewWithNoBio
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.NewWithoutNoBio
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.ws
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.wsrsol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL5.3934.L2595
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL5.3934.L2729
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.comb2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.combFrz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.comb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.comb.v2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.c.v2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.a.v2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.a.v3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.b.v2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.b.v3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.combFrz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.comb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.c.v3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v2.bis
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v2.diag
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL4.4067.L609
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL5.4067.L608.flp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL5.4067.L608
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL5.4067.L609
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/DEVT/ref3789/FG2.NOfracnobio
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/DEVT/ref3789/FG2.WITHfracnobio
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG1low.CWRR.3934
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG1low.CWRR.3934.NewWithoutNoBio
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG1translow.CWRR.3934
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG2low.CWRR.3934
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG2low.CWRR.3934.wsrsol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb4
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb.Frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1translow.CWRR.3977.comb.Frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1translow.CWRR.3977.comb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1translow.CWRR.3977
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG2low.CWRR.3977.comb.Frz
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG2low.CWRR.3977.comb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG2low.CWRR.3977
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG3WFDEIv1.comb
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG3WFDEIv1.combwithoutrsol
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG3WFDEIv1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref4067/FG3WFDEIv1.4067.flp
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref4067/FG3WFDEIv1.4067
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM5A2/DEVT/pdControl/CPL01-5A2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/abrupt4xCO2/CM6010.2-LR-4xCO2-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/abrupt4xCO2/CM608P-LR-4xCO2-ACC-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TAC-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TAC-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TMAF-1M-R
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TMAF-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TOCE-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TOCE-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1.TEST-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1.TEST-LR-pdCtrl-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2.fallv-LR-pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2.fallv-LR-pdctrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-cdrag1
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-cdrag8
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-hmin50
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-newmy
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-T9-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-M2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-M3
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-Y2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-Z2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TNO9-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TNO9-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TNOO-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6062-LR-pdCtrl-365NRM
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6062-LR-pdCtrl-C02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6062-LR-pdCtrl-C04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607.3.1-LR-pdCtrl-01-MAF
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-D01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-DY2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-NY2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-U01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPACC-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPACC-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPACC-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPLUS-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-C01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-ICEPLUS-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/PROD/abrupt4xCO2/CM607-LR-4xCO2-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/PROD/pdControl/CM606-LR-4xCO2-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/PROD/pdControl/CM606-LR-pdCtrl-C03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/TEST/pdControl/CM608-LR-pdCtrl-MAF-TEST-1M
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/TEST/pdControl/CM608-LR-pdCtrl-MAF-TEST-1Y
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/TEST/pdControl/CM608-LR-pdCtrl-MAF-TEST-Y2
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM5A2/DEVT/piControl/H6k5A-Vlr01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM5A2/PROD/midHolocene/H6k5A-Vlr02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM5A2/PROD/midHolocene/H6k5A-Vlr03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/lgm/CM606-LR-lgm-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.2.riv00N-LR-pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.2.riv07N-LR-pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.2.riv09N-LR-pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.runoff09-LR-pdctrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.calv-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.calv-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.dt15-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.dt20-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM606.dt20-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM606-LR.test-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM607.cplfreq-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM609.v3-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM609.v3-LR-pdCtrl-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM609.v3-LR-pdCtrl-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/TPATCH
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V05
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V06
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V07
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V08
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/PROD/abrupt4xco2/CM605.dt15.LR-4xCO2-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SCdamax-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SCdhstar-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwAlb-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwAlb-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwAlb-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdTKE-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdTKE-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdv2o-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdv2o-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCnd05-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCnd05-2b
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCnd05-2I
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCndv2-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-TSnw-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-amaxn-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-amaxs-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gkall08-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gkdrag08-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gklift08-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gkwake08-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-nobugK-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-nobugKA-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-pstar-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-SnwAlb-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-SnwAlb-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-02
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-04
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw2-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw2Tsb-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3TP-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3TPaA-01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3TPaA-03
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/IPSLCM6/DEVT/pdControl/CPL01
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/DEVT/clim/CM605-LR-sstClim
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/PROD/clim/CDO55
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/PROD/clim/TLC45
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/PROD/clim/TLC45.T70
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/EXP1114_all_REG
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/EXP1114_noAnth_REG
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/HIGH_REG_PKUBC
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/LOW_REG_PKUBC
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/Nreg_test2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/Nreg_test3
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_ACCMIP
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_noanth
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_noChi_PKU
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_noEF
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_noEFSDM
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_nofire
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_onlyChina
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_PKUBC2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_PKUBCf
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REG_PKUBCi
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGt1
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_2noEFSDM
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_ACCMIP
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_high
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_low
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_newSO2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_noanth
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_noChina
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_noEF
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_noEFSDM
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_noIndia
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_noSDM
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_PKUBC
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/REGUL_update
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/S0_REGUL
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/S1_REGUL
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/S2_REGUL
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/S3_REGUL
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_0623_old
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_0624_1
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_06Octc
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_07JUNEd
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_07OCTa
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST1
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/test1_SO2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/test_HIGH_REG
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_MAYa
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_NEW_START2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_NEW_START3
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/TEST_NOVa
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24balk/LMDZORINCA/AER/zAS_ACCMIP
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24bous/LMDZORINCA/GES/ap_bousq2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24bous/LMDZORINCA/GES/ap_Tiedtke2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24bous/LMDZORINCA/GES/ap_Tiedtke3
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24bous/LMDZORINCA/GES/ap_Tiedtke5
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24bous/LMDZORINCA/GES/ap_Tiedtke7
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24bous/LMDZORINCA/GES/ap_Tiedtke
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH07n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH08n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH09n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH09ns1
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH09ns2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH09ns4
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH09ns5
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH09ns6
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH10nEC
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH10nhr
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH10n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH11n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH11nRP
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH12n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH13nhr
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH13n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH14n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH15n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH16n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH17n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH17nnh3
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH17nnox
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH17nso4
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH18n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH19nhr
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH19n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH20n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH21n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH22n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH23n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH24n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH25n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH26n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH27n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH28n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH30n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH31n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH32n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH33n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH34n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24haug/LMDZORINCA/NMHC_AER/LOI_DH35n
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24lava/LMDZORINCA/NMHC_AER/L5OI4runPRODLOSSSophie.0
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24lava/LMDZORINCA/NMHC_AER/L5OI4runPRODLOSSSophie.11
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24lava/LMDZORINCA/NMHC_AER/L5OI4runPRODLOSSSophie.5
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24lava/LMDZORINCA/NMHC_AER/L5OI4runPRODLOSSSophie.6
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24lava/LMDZORINCA/NMHC_AER/L5OI4runPRODLOSSSophie.7
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24lava/LMDZORINCA/NMHC_AER/L5OI4runPRODLOSSSophie.8
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24locat/LMDZORINCA/GES/np_2000_test
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24long/LMDZORINCA/INJ/INJDTR
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24long/LMDZORINCA/POLMIP/POLD4
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p24long/LMDZORINCA/POLMIP/POLMIPH
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sepul/DEVT/piControl/coupltuningVLR.00
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kIST.ZEur.veg39k.SU3
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kIST.ZEur.veg39k.SU.SstUM
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kST.ZEur.veg2000.SU
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kST.ZEur.veg39k.SU1
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kST.ZEur.veg39k.SU3
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kST.ZEur.veg39k.SU4
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.39kST.ZEur.vegPSep
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p25sima/LMDZORINCA/AER/LOImr19.LGM.ZEur.veg39kST.SU
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p529vui/OL2/DEVT/OBS
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L4OI3NA_39_G
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L4OI3NA_39
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L4OI4NA_39
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L5OI3NA_39_Gbis
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L5OI3NA_39_G
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L5OI3NA_39
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/L5OI4NA_39_G
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI3NA_19_clim
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI3NA_19_G2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI3NA_19
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI3NA_beta1
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI3NA_beta2
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI4NA_19_clim
https://vesg.ipsl.upmc.fr/thredds/catalog/work/p86cozic/LMDZORINCA/NMHC_AER/LOI4NA_19
`;
