var input = `
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/AirsT0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Cosp0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010fallv/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010Fallv/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6010/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607Calot/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotMY1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotMY2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotMY33/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotOrogr/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotT0cosp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotT1cosp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotT2cosp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotTeta/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotTglace240/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CalotTglace250/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvAdiab/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvClosTh/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvCtrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvCtrlT0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvCtrlT1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvTop/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607CvWk/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ607svn2761/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v2Bds/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v3Ctrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v3T1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v4/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v5/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6lc23/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6oro/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6svn2828/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6tqsat/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6wb3p05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05MyLmGust/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05MyLm/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ608v6Wb3P05MY/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6103bFlagPbl12/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ6103b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZ610v3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.4/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.5/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.70a/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.70aZ0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/LMDZv5.80B/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70bOrolf/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2703/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2709Cosp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2709cv72/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.70svn2709/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80aa2714/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80aa/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Acv48/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Adtphy10cv72/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Adtphy10/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80A/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80B/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.80Bz0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81clos1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81clos2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81rim1cv48/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81rim1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.81rim2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82alw/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82gkwak/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82svn2738/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/NPv5.82svn2739alw/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Calipso/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Cloudsat/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Isccp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Misr/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00Modis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp00/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/aidel/LMDZOR/DEVT/clim/Tcosp01Subcln/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/ducharna/OL2/PROD/test3977/FG3WFDEIv1.new2combrsol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/ducharna/OL2/PROD/test3977/FG3WFDEIv1.newcombnorsol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/ducharna/OL2/PROD/test3977/FG3WFDEIv1.newcombrsol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/0aerstrat/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/EXP01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/oa5a/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/oa5b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/pdControl/vol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/DEVT/piControl/EXP00/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/IPSLCM6/PROD/pdControl/CM606-LR-pdCtrl-C03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.40RRTMsvn2456AER0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1DUST6w/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1DUST6wT/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1ORG2w/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1ORG6w/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1ORG/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT2w/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT6wa/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT6w/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/hurm/LMDZOR/DEVT/clim/NPv5.50berg1SOOT/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.30Y.2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.q/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM607-LR.rt0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM608-LR.30Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIP-CM608-LR.q2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPg-CM608-LR.30Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPgv-CM607-LR.30Y.2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPg.vt-CM607-LR.2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80bz0cwrr/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80bz0cwrr.q2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80-CM606-LR-b01bz0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80-CM606-LR-b01bz0.q/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/AMIPNPv5.80-CM606-LR-b01bz0.q.rt0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM608-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM608-LR-amip-G-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM609-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM609-LR-amip-01.q/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/mellull/LMDZOR/PROD/amip/CM609-LR-amip-G-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24balk/LMDZORINCA/DEVT/AER/Historical/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24balk/LMDZORINCA/PROD/AER/pdCtrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24balk/LMDZORINCA/PROD/AER/preInd2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6.0.10.04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6.04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05.2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis4/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05bis5/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-pdCtrl-05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-piCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-07/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-08/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZORINCA/PROD/AER/LOI6-LR-Y-09/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZOR/PROD/clim/LMDZOR02bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZOR/PROD/clim/LMDZOR02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p24cozic/LMDZOR/PROD/clim/LMDZOR03bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p25sepul/IPSLCM5A2/PROD/piControl/pi.orch.07.tun00/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p25sepul/IPSLCM5A2/PROD/piControl/speedtest.cmip6/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-etaumle/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nnetau0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nolnmle/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-rnffwb0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-rnffwb2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607.calving-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-CALMOC-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-CalvIce-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-CalvIce-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p48ethe/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-CalvIce-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.dynroot/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.frz.frzc1.smtc2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729.frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref3977/CL4.3977c.L2729/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/LMDZOR/PROD/ref4365/CL4.4365.L2883/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.10spinup/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.cruncep.spinup/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.veg.const/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA1.veg.update/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA2.cruncep.vegconst/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA2.cruncep.vegupdate/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.cruncep.spinup/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.cruncep.vegconst/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.cruncep.vegupdate/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.spinup/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.vegconst/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.vegupdate/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/ESA3.wfdei.vegupdate.nodr/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.CWRR.3977c.comb.nors.bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.CWRR.3977c.comb.nors.dynroot/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.gswp3.CWRR.3977c.comb.Frz.frozc1.smtotc2.rsol.dynroot/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.gswp3.CWRR.3977c.comb.nors.Frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/FG2low.gswp3.CWRR.3977c.comb.nors/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/test.esa.loc/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref3977/test.wfdeilatlon.loc/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.frz.dynroot/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.ks/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/OL2/PROD/ref4365/FGlow.gswp3.4365.usda/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.frz.dynroot/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.ks/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529bast/ref4365l2883/PROD/amip/CL4.4365.L2883.usda/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nudgeUV12h/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-nudgeUV/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.GUST.1-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.GUST-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.Z0-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.Z0.pstar10e3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM605.Z0.rnalbice058/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.Z0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.Z0.r2641bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM606.Z0.trunk/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-gust-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-INIT-3DOCE/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-nudgeUV/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-nudgeUVT/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM607-NUDTS-3DOCE/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-G/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-G-nudUV/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-Gust/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-Gust-nudUV12/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-Gust-nudUV/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-FOR-ENSEMBLE/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-fqsat-Gust-nudUV12h/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-Gust-bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-Gust/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-Gust-nudUV12h/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/IPSLCM6/PROD/pdControl/CM605.Z0-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/amip/ERAI.CTRL.NUD/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/amip/LMDZOR.NUD.ERAISST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIP-CTRL/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-fdoce0.8/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-fdoce1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-nudUV12h/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-nudUV24h/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-AMIPG-nudUV/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-amip-Gust/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CM608P-LR-amip-Gust-nudUV/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CTRL6.0.5b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CTRL6.0.5F/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/CTRL6.0.5.foce/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR6.0.5GUST.1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.CTRL/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.3wk/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.fdrag0.9/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.minwind/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.GUST.strato/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.609v4.Z0heqZ0m/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.GUST.NUD.fqsat/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.GUST.NUD/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/LMDZOR.pre608G/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/NPv5.8GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/NPv5.8Z0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.GUSTB/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.GUST.ratqs/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5b.Z0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5bZ0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5.GUSTBF/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5.GUSTF/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/DEVT/clim/V6.0.5.Z0F/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.AMIP/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST.3wk/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.GUST.strato/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/AMIP.NUD.VS.buoy/LMDZOR.NUD.Z0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.CLIM/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.CTRL/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST.2bl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST.cdrag/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST.minwind/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.CTRL.2004/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.CTRL.2007/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.CTRL/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST0wk/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST.2004/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST.2007/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST3wk.2007/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST3wk/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.GUST.strato/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.strato/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.Z0.2004/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.NUD.Z0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.Z0.cdrag/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.Z0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p529tra/LMDZOR/PROD/LMDZOR.vs.buoy/LMDZOR.Z0.qh/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86cadul/IPSLCM6/DEVT/pdControl/TCO2.00/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86cadul/IPSLCM6/DEVT/pdControl/TCO2.01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86cadul/IPSLCM6/DEVT/pdControl/TCO2.02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/pdControl/CM5A2-BILAN07/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/pdControl/CM5A2-BILAN08/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/pdControl/CM5A2-BILAN-NEWOASIS01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2.1-piControl.02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK-rev2642/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK-rev26621-bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/CM5A2-TRUNK-rev26621/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/DEVT/piControl/COURSNIV2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/pdControl/CM5A2-BILAN01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/pdControl/CM5A2-BILAN02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/pdControl/CM5A2-BILAN03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/piControl/CM5A2.1-piControl.03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM5A2/TEST/piControl/VERIFIPSLCM5A2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/historical/CM607-LR-historical-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/historical/CM607-LR-historical-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.1.ener-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.2.test-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.albedo-LR-pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.cdrag-LR-pdctrl-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.cld-LR-pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.cld-LR-pdctrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010-LR-pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.Ridging-LR-pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.Ridging-LR-pdctrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.Ridging-LR-pdctrl-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.SnwCnd-LR-pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.SnwCnd-LR-pdctrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM6010.SnwCnd-LR-pdctrl-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM605-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM605-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM605.THC1-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606.calving-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606.calving-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan06/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-bilan07/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs06/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs07/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs08/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs09/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs10/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs11/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs12/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs13/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs15/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs16/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-perfs17/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.4-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.5-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.interp-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.interp-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607.lmixmin-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM608-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609.xios-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609.xios-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/CM609.xios-LR-pdCtrl-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/PRECM607/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/pdControl/v2.CM6.0.4-pdctrl.0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM6010.2-LR-piCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM605-LR-piCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM607-LR-piCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/CM607.spinup-LR-piCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/PRECM5A2.6/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/IPSLCM6/DEVT/piControl/PRECM5A2.7/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM606-LR-amip-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM607-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/amip/CM607-LR-amip-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/LMDZOR/DEVT/clim/CM606-LR-amip-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/OL2/DEVT/secsto/MYEXP2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86caub/OL2/DEVT/secsto/MYEXP3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-FREEZE-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/pdControl/CM607-DISSIP-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/pdControl/CM607-EMBD2-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/DEVT/piControl/WF.01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605-LR-amip-05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-LR-amip-05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/amip/CM605.SUN-OZ-LR-amip-05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605-FREEZ-LR-sstClim-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605-LR-sstClim-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605.NOSU-LR-sstClim-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM605-OZ-LR-sstClim-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/clim/CM606-OZ-LR-sstClim-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-FREEZ-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-pstar10e3-pdCtrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-rnalbice058-pdCtrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86denv/IPSLCM6/PROD/pdControl/CM605-tglacemin253-pdCtrl/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6.0.10.1Test-Pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6.0.10.1Test-Pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6.0.10.3b-Pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6011pre-LR-pdCtrl-fallv-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6011pre-LR-pdCtrl-fallv-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM6011pre-LR-pdCtrl-fallv/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01a/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01bz0-cplok/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM606-LR-pdCtrl-b01bz0/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.2-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.2mod-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.3.1-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.3.1mod-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607.3-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR.newmy/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01cont/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-2bands-lucia/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-2bands/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-bQP037-GWD/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-bQP037/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-NPv6.0.7/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt14/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt16-lucia/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt16/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-opt16oce/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-optim/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-rim1607b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR.spin.newmy/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM607-LR.TRY/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608.3-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608.6-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608-LR-pdCtrl-gwdrag01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM608-LR-pdCtrl-gwdrag02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-fcdragoce/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/CMpre6010.4-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/DEVT/pdControl/lucia/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/PROD/pdControl/NPv5.70PDctrl01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/PROD/pdControl/NPv5.70PDLott/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/IPSLCM6/PROD/pdControl/v5.71vd2qsp375/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.2bands.full/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.2bands/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.2bands.opt/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86fair/LMDZOR/TEST/clim/CM607-LR.3bands/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-gkdrag2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-gkwake4/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607divx2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607gkdrag/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607gklift/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607gkwake/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607grotJM/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607grottempJM/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607ion/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607iterdiv2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607OrogAll/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607OrogFC/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ggas/LMDZOR/DEVT/clim/LMDZ607tempJM/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01contspin/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/CM607-LR-pdCtrl-01spin/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/M607.veget-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/IPSLCM6/DEVT/pdControl/M607.veget-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM6010/createsnow/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m10b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m11b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m1b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m2b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m3b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m4b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m5b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m6b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m7b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m8b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.m9b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.refb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/DEVT/CM609climpdcontrl/CM609.src3013b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3047/CL4.4067.L608.flp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3047/CL4.4067.L608/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.NewWithNoBio/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.NewWithoutNoBio/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.ws/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL4.3934.L2595.wsrsol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL5.3934.L2595/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3934/CL5.3934.L2729/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.comb2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.combFrz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.comb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.comb.v2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL4.3977.L2729.c.v2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.a.v2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.a.v3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.b.v2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.b.v3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.combFrz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.comb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.c.v3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v2.bis/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v2.diag/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref3977/CL5.3977.L2729.v3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL4.4067.L609/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL5.4067.L608.flp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL5.4067.L608/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/LMDZOR/PROD/ref4067/CL5.4067.L609/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/DEVT/ref3789/FG2.NOfracnobio/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/DEVT/ref3789/FG2.WITHfracnobio/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG1low.CWRR.3934/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG1low.CWRR.3934.NewWithoutNoBio/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG1translow.CWRR.3934/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG2low.CWRR.3934/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3934/FG2low.CWRR.3934.wsrsol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb4/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb.Frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977.comb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1low.CWRR.3977/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1translow.CWRR.3977.comb.Frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1translow.CWRR.3977.comb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG1translow.CWRR.3977/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG2low.CWRR.3977.comb.Frz/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG2low.CWRR.3977.comb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG2low.CWRR.3977/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG3WFDEIv1.comb/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG3WFDEIv1.combwithoutrsol/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref3977/FG3WFDEIv1/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref4067/FG3WFDEIv1.4067.flp/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86ghatt/OL2/PROD/ref4067/FG3WFDEIv1.4067/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM5A2/DEVT/pdControl/CPL01-5A2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/abrupt4xCO2/CM6010.2-LR-4xCO2-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/abrupt4xCO2/CM608P-LR-4xCO2-ACC-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TAC-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TAC-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TMAF-1M-R/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TMAF-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TOCE-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1-LR-pdCtrl-TOCE-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1.TEST-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.1.TEST-LR-pdCtrl-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2.fallv-LR-pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2.fallv-LR-pdctrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-cdrag8/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-hmin50/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-newmy/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-T9-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-M2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2-LR-pdCtrl-TMAF-M3/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-Y2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TMAF-Z2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TNO9-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TNO9-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6010.2R-LR-pdCtrl-TNOO-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6062-LR-pdCtrl-365NRM/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6062-LR-pdCtrl-C02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM6062-LR-pdCtrl-C04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607.3.1-LR-pdCtrl-01-MAF/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-D01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-DY2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-NY2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM607H-LR-pdCtrl-U01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPACC-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPACC-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPACC-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM608P-LR-pdCtrl-ICEPLUS-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-C01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-ICEPLUS-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/PROD/abrupt4xCO2/CM607-LR-4xCO2-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/PROD/pdControl/CM606-LR-4xCO2-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/PROD/pdControl/CM606-LR-pdCtrl-C03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/TEST/pdControl/CM608-LR-pdCtrl-MAF-TEST-1M/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/TEST/pdControl/CM608-LR-pdCtrl-MAF-TEST-1Y/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86maf/IPSLCM6/TEST/pdControl/CM608-LR-pdCtrl-MAF-TEST-Y2/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM5A2/DEVT/piControl/H6k5A-Vlr01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM5A2/PROD/midHolocene/H6k5A-Vlr02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM5A2/PROD/midHolocene/H6k5A-Vlr03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/lgm/CM606-LR-lgm-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.2.riv00N-LR-pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.2.riv07N-LR-pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.2.riv09N-LR-pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM6010.runoff09-LR-pdctrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.calv-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.calv-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.dt15-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM605.dt20-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM606.dt20-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM606-LR.test-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM607.cplfreq-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM609.v3-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM609.v3-LR-pdCtrl-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/CM609.v3-LR-pdCtrl-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/pdControl/TPATCH/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V05/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V06/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V07/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/DEVT/piControl/VLRLIM3V08/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mart/IPSLCM6/PROD/abrupt4xco2/CM605.dt15.LR-4xCO2-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SCdamax-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SCdhstar-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwAlb-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwAlb-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwAlb-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdTKE-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdTKE-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdv2o-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCdv2o-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCnd05-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCnd05-2b/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCnd05-2I/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-SnwCndv2-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM607R-LR-pdCtrl-TSnw-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-amaxn-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-amaxs-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gkall08-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gkdrag08-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gklift08-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-gkwake08-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-nobugK-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-nobugKA-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-pstar-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-SnwAlb-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-SnwAlb-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-02/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-sso-gk-04/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw2-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw2Tsb-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3TP-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3TPaA-01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86mign/IPSLCM6/DEVT/pdControl/CM609-LR-pdCtrl-TSnw3TPaA-03/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/IPSLCM6/DEVT/pdControl/CPL01/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/DEVT/clim/CM605-LR-sstClim/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/PROD/clim/CDO55/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/PROD/clim/TLC45/MONITORING
https://vesg.ipsl.upmc.fr/thredds/catalog/work_thredds/p86musat/LMDZOR/PROD/clim/TLC45.T70/MONITORING
`;
